# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [17]:
#solved
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[4,5,6],[1,2,3],[2,5,8]])
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1 + mat2)
print("\nMultiplication\n------------------\n", mat1 * mat2)


print("\nDivision\n------------------\n", mat1 / mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", (3*mat1) - (2*mat2))


print("\nAddition of a scalar (100)\n-------------------------\n", np.add(mat1,100))


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n", np.power(mat1, 0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 5 6]
 [1 2 3]
 [2 5 8]]

Addition
------------------
 [[ 5  7  9]
 [ 5  7  9]
 [ 9 13 17]]

Multiplication
------------------
 [[ 4 10 18]
 [ 4 10 18]
 [14 40 72]]

Division
------------------
 [[0.25  0.4   0.5  ]
 [4.    2.5   2.   ]
 [3.5   1.6   1.125]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-5 -4 -3]
 [10 11 12]
 [17 14 11]]

Addition of a scalar (100)
-------------------------
 [[101 102 103]
 [104 105 106]
 [107 108 109]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  1   8  27]
 [ 64 125 216]
 [343 512 729]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [109]:
from numpy.random import randint as ri
mat1 = ri(10,size=(3,3))
mat2 = ri(10,size=(3,3))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.product(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.product(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(100,size=(3,3))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 0 3]
 [5 4 0]
 [1 5 2]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 6 9]
 [4 7 3]
 [9 5 4]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 25

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [11  9  5]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [8 9 8]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 0  0 10]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 72 210 108]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 2.7777777777777777

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 1.9876

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [18]:
##Solution...solved
samp_mat = np.ones((3,3))
samp_mat.reshape(9,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

### 4.Sort

In [38]:
#solved
A = np.random.randint(100, size=10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [81 73 84 52 68 91 73 19 70 60]

Here is the sorted vector
 -------------------------------------------------- 
 [19 52 60 68 70 73 73 81 84 91]


In [43]:
#solved
M = np.random.randint(100, size=(5,5)) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[84  5 28 17 69]
 [12 87 67 12 44]
 [61 68 44 91 96]
 [61 42  4  7 23]
 [59 64  9 44 99]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 5 17 28 69 84]
 [12 12 44 67 87]
 [44 61 68 91 96]
 [ 4  7 23 42 61]
 [ 9 44 59 64 99]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[12  5  4  7 23]
 [59 42  9 12 44]
 [61 64 28 17 69]
 [61 68 44 44 96]
 [84 87 67 91 99]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [49]:
# solved
# Fill the following ***** with appropriate solution.
a=np.random.randint(100,size=10)
b=np.random.randint(100,size=10)
c=np.random.randint(100,size=10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.max(a))
print("Max of b:", np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))



a: [56 38  9 40 79 69  7 71  0 33]
b: [69 39 26 32 29 63 40 22 30 19]
c: [80 58 90 34 52 61 69 88 48  4]
Max of a: 79
Max of b: 69
Max of a location: 4
Max of b location: 0
Max of c location: 2
Max of a: 79
Max of b: 69
Max of a location: 4
Max of b location: 0
Max of c location: 2


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [54]:
#solved
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(10,size=(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.power(mat1,0.5))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.power(mat1,2))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.remainder(mat1,2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[0 9 4]
 [1 1 8]
 [8 3 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 1 2]
 [9 5 6]
 [9 4 6]]

Sq-root of 1st matrix using np
------------------
 [[0.         3.         2.        ]
 [1.         1.         2.82842712]
 [2.82842712 1.73205081 1.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 0 81 16]
 [ 1  1 64]
 [64  9  1]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[      -inf 2.19722458 1.38629436]
 [0.         0.         2.07944154]
 [2.07944154 1.09861229 0.        ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[0 1 0]
 [1 1 0]
 [0 1 1]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log
  


### 7.Generating matrices from distributions

In [68]:
np.random.rand(2,3)

array([[0.64233833, 0.50051757, 0.66654331],
       [0.33754673, 0.39576521, 0.60009506]])

In [113]:
mu, sigma = 0, 1 
a = np.random.normal(0, 1, 100)
a.std()

0.9165706631422691

In [118]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.normal(0, 1, 100))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.rand(1,100)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.multinomial(20, [1/6.]*6, size=1)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.53311003 0.64295922 0.53331801]
 [0.43533119 0.65438272 0.95908621]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[ 2.94884417  0.57099289  2.25332342  1.24572637 -0.81365535 -0.38803336
  0.33387478  0.01462097 -1.32388227 -0.85457989  0.28139407 -0.65114171
  0.16521923  0.25602347  0.04117889 -0.76751837  3.03388688  0.08849204
  0.77250402 -0.21562119  0.08296669 -1.02652845 -1.03269955  0.43287069
 -0.51901827 -0.34927897  0.0130397   0.37876349 -0.0846213   0.12160921
  0.95394663 -0.95297255 -0.83062764  0.2343165  -1.18160419 -0.07085649
 -2.79185082 -0.5354      0.76488729 -0.35870271  0.25355339  0.5744833
 -1.47971283  0.30173229  0.46682587 -0.58706873  0.02079826 -1.61240317
 -0.96517723  0.62127167 -1.21129369 -1.01316184  0.67813193 -0.26855044
  0.13309015  0.28842337  0.58574227 -1.27204166  1.21861784 -1.46261825
 -0.27557503 -1.01578307 -0.1510371  -1.45182801 -0

### 8.Find the nearest value from a given number in an array using NumPy.

In [66]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
sam = np.random.randint(12, size=5)
print (sam)
diff = np.subtract(sam,10)
print(diff)
i = np.argmax(diff)
print("index where difference is minimum", i)
print("the element",sam[i])

[3 4 7 7 8]
[-7 -6 -3 -3 -2]
index where difference is minimum 4
the element 8


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [97]:
mat = np.array([0,1,2])
print(mat)
m1 = np.subtract(mat,mat)
print(m1)
m2 = np.add(mat,mat)
print(m2)
sam1 = np.column_stack((m1, mat, m2))
print('_'*10, '\n', sam1)

[0 1 2]
[0 0 0]
[0 2 4]
__________ 
 [[0 0 0]
 [0 1 2]
 [0 2 4]]
